blog/clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('users.urls'))
   

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/users/urls.py
from django.urls import path, include
from users.views import Register
from .import views


urlpatterns = [path('', include('django.contrib.auth.urls')),
               path('register/', Register.as_view(), name='register'),
               path('',  views.PostView.as_view(), name='home'),
               path('add/',views.addpost, name='add'),
                path('<int:pk>/',views.PostElement.as_view()),
                path('del/<int:pk>/',views.DelElement.as_view(), name='del'),
                path('comments/<int:pk>',views.AddComments.as_view(), name='comment'),
                path('<int:pk>/add_likes/',views.AddLike.as_view(), name='add_likes'),
                path('<int:pk>/del_likes/',views.DelLike.as_view(), name='del_likes'),
                path('api/v1/postlist/<int:pk>',views.PostCRUD.as_view(), name='serializ'),
                path('api/v1/postlist/',views.PostAPIlist.as_view(), name='serializall'),
                path('movies/',  views.MoviesView.as_view(), name='movie'),
                path('change/',  views.changepas, name='change')
                
                     ]

blog/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime  


# Create your models here.
class PostQuerrySet(models.QuerySet):
    def titles(self):
        return self.order_by('-dats')

class Post(models.Model):
    title = models.CharField('Заголовок записи', max_length=100)
    descript = models.TextField('Текст блога')
    author = models.CharField('Имя автора', max_length=100)
    dats = models.DateTimeField(default=datetime.now())
    
    img = models.ImageField('Изображение', upload_to = 'image/%Y')# c указанием текущего года, это путь где будут храниться все излбражения с админки
    
    objects =  PostQuerrySet.as_manager()
    
    def __str__(self):
        return f'{self.title}, {self.author}' #отображение в списке всех записей в админке
    
    
    class Meta:
        verbose_name = 'Запись' #красивое отображение  в админке
        verbose_name_plural = 'Записи'
        

class Comments(models.Model):
    name = models.CharField('Имя автора', max_length=100)
    textcom = models.TextField('Комментарий', max_length=2000)
    post = models.ForeignKey(Post, verbose_name="Публикация",on_delete=models.CASCADE, related_name='compos') #связь с моделью публикацийь при удалении - каскад - удаляется и комментарий к публикации
    
    def __str__(self):
        return f'{self.name}, {self.post}' #отображение в списке всех записей в админке
    
    class Meta:
        verbose_name = 'Комментарий' #красивое отображение  в админке
        verbose_name_plural = 'Комментарии'


class User(AbstractUser):
    pass

class Likes(models.Model):
    ip = models.CharField('IP-адрес', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Понравившееся', on_delete=models.CASCADE)
    
    
    
class Dressingroom(models.Model):
    num = models.CharField('Номсер гримёрки', max_length=100)
    
    def __str__(self):
        return f'{self.num}'
    
class Director(models.Model):
    dirname = models.CharField('Имя режисёра', max_length=100)
    
    def __str__(self):
        return f'{self.dirname}'
    
class Movie(models.Model):
    title = models.CharField('Имя актёра', max_length=100)
    direc = models.ForeignKey(Director,on_delete=models.CASCADE, null = True, blank=True, related_name='moviess')

    def __str__(self):
        return f'{self.title}, {self.direc}'
    
class Actor(models.Model):
    name = models.CharField('Имя актёра', max_length=100)
    dress = models.OneToOneField(Dressingroom, on_delete=models.CASCADE, null = True, blank=True)
    mov = models.ManyToManyField(Movie, related_name='connect')
    
    def __str__(self):
        return f'{self.name}, {self.dress}'
    

blog/templates/addposts.html
{%extends 'home.html'%}
    {%load static%}
    {%block content%}
    <div>
      <h3 style='display: flex;
      /* flex-direction: row-reverse; */
      position: relative;
      justify-content: center; font-size: 25px;'>Добавить пост</h3>
      <hr>
      
      <form method="POST" enctype="multipart/form-data" id='addp'>
        {% csrf_token %}
        <div class='addtext'>
          
          <input type="text" name="title" maxlength="100" required="" id="id_title" placeholder="Название поста"><br>
          <br>
          <textarea name="descript" cols="40" rows="10" required="" id="id_descript" placeholder="Содержание поста"></textarea> <br>
          <br>
          <input type="text" name="author" maxlength="100" required="" id="id_author" placeholder="Ваше имя"><br>
          <br>
          
          <br>
          {{form.img}} <br>
        </div>
       
      
        

        
        <button type="submit" class='addbut'>Отправить</button> <br>

    </form>


    </div>

   {%endblock%}

blog/templates/base.html
{%extends 'home.html'%}
    {%load static%}
    {%block content%}
    <form  action='{%url "home"%}' style='display: flex;
    flex-direction: row-reverse;'>
    
      <input class="searching" type="search" placeholder="Search" aria-label="Search" name='search'>
      <button class="btno" type="submit">Search</button>
    </form>
    
  

    {%if post_list%}
      {%for post in post_list%}
      <div id='mainblock'>
        <div id='post'>
          <h2 class='headelement'><a style='color:grey;' href='{{post.id}}'>{{post.title}}</a></h2>
        <hr>
        <br>
        {%if post.img.url%}
          <div class='block'><img class='pic' src="{{post.img.url}}">
        {%endif%}
        <p class='descr'>{{post.descript}}<p></div>
        <br>
        <hr>
        <p class='aut'>{{post.author}}<p>
        </div>
      </div>
  
      {%endfor%}
    {%else%}
      {%if user.is_authenticated%}
        <p class="empty"><a href='{%url "add"%}'>ADD FIRST POST!</a></p>
      {%else%}
        <p class="empty"><a href='{%url "login"%}'>LOGIN TO ADD FIRST POST!</a></p>
      {%endif%}

      

    {%endif%}  

   
    {%endblock%}

 

    

blog/templates/blogelement.html
{%extends 'home.html'%}
{%load static%}
  {%block content%}
  
  <body>
    <a  href='{%url "home"%}'><img style = 'width: 30px;'src='https://sun9-65.userapi.com/impg/aVNXjc8e0eDTHRJW_Px_XgYCHAbQU9QwlTiZ9A/eeREHI7tT60.jpg?size=512x512&quality=95&sign=87ecba353756021f6f704fc005b95599&type=album'/></a>
    <div id='mainblock'>
      
      <div id='post'>
        
        <h2>{{post.title}}</h2>
      <hr>
      <br>
      <div class='block'><p align='center'><img class='pic' src="{{post.img.url}}" wigth='50%'></p>
      <p class='descr'>{{post.descript}}<p></div>
      <br>
      <hr>
      <p>{{post.author}}<p>
      </div>
    </div>
    <div>
      <p style='font-weight: bold;'><a href={%url "add_likes" post.id%} style='font-size: 30px;'>❤ </a>
        <p style='font-weight: bold;'><a href={%url "del_likes" post.id%} style='font-size: 30px;'>❤ </a>
        Понравилось: {{post.likes_set.all.count}}</p>

      


      
      

    </div>
    {%if user.is_superuser%}
    <div><a href='{%url "del" post.id%}'> del</a></div>
    {%endif%}
      
      <div id = 'create'>
        <hr>
        <a class = 'com'href='#'>Оставить комментарий</a><br><br>
        <form action='{%url "comment" post.id%}' method='post'> <!--ссылка на вьюху-->
            {% csrf_token %}
            
            <textarea class='men'name='textcom' placeholder="Ваш комментарий"></textarea><br> <! ссылка на поле в модели админки, чтобы данные попав во вью занеслись в админке>
            
            <input class='inp' type='text' name ='name' placeholder="Ваше имя"><br>
            <button class = 'sub' type='submit'>Опубликовать</button>

        </form>
        
      </div>
      <h3 class='headcomm'>Комментарии</h3>
      <div id = 'comm'>
        {%for comment in post.comments_set.all%}
        <div='onecom'>
            <h3>{{comment.name}}</h3>
            <p>{{comment.textcom}}</p>
            <hr> <!--отобразить комы на странице-->


        </div>

        {%endfor%}

      </div>


  {%endblock%}

blog/templates/change.html
{%extends 'home.html'%}
{%load static%}
{%block content%}

<form action = '{%url "change"%}' method = 'post' id='change'>
    {% csrf_token %}
    {{msg}}
    <div class='form-group'>
        <label> Enter the current username</label>
        <input  class='form-control' type='text' name='old'>
    </div>
    <div class='form-group'>
        <label> New password</label>
        <input class='form-control' type='password' name='newp'>
    </div>
   
    <div class='form-group'> 
        <input type='submit' value='change' id = 'sb'>
    </div>




</form>
{%endblock%}

blog/templates/home.html
{%load static%}

<head>
  <meta charset="UTF-8">
  <title>Мой косплей блог</title>
  <link rel='stylesheet' href = "{%static 'css/stil.css'%}"  type='text/css' media='all'/>
</head>

<body>
  

    <h1 id='head'><a href='{%url "home"%}'>teLLMe</a></h1>
    <p class='us'>Hello, {{user}}!<p>

    {%if user.is_authenticated%}
        <div class='lin'><a href='{%url "logout"%}'>Logout</a> | <a href='{%url "add"%}'>Add post</a></div>
        <div class='lin'><a href='{%url "change"%}'>Change password</a> </div>

        
    {%else%}
        <div class='lin'><a href='{%url "login"%}'>Login</a> | <a href='{%url "register"%}'>Registrate</a> </div>
        <div class='lin'><a href='{%url "change"%}'>Change password</a> </div>
        
    {%endif%}
    {%block content%}

    {%endblock%}

blog/templates/movie.html
{%load static%}
{%for pos in post%}
{%for p in pos%}
{{p}}
{%endfor%}
{%endfor%}